# Generated by Django 5.2.6 on 2025-09-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Noon', 'Noon'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=10)),
                ('section', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=10)),
            ],
        ),
    ]
