# Generated by Django 5.2.6 on 2025-09-19 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('pet_type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.package')),
            ],
        ),
    ]
